level = [
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "W                          WWWW    ",
    "W         WWWWWW   WW   WWWWWW  WWW",
    "W   WWWW       W   WWW  WW     WWWW",
    "W   W        WWWW  WWWWWW         W",
    "W WWW             WWW       WWW  WW",
    "W   W     W W   WWWWWW WWWWWWWWWWWW",
    "W   W     W   WWW WW        WWWWWWW",
    "W   WWW WWW   W W  W   WWW   WW    ",
    "W     W   W   W W  W  WW    W WWWWW",
    "WWW   W   WWWWW W  W WWW    W WWWWW",
    "W W      WW        W WWWW  WWWW  WW",
    "W W           WWW   W           WWWW",
    "W     W    E   W   W WWWWWWWWWWWW W",
    "     WWWWWWWWWWWWWWW  WWW  WW    WW",
    "                 WW   WW     W    W",
    "WW          W           W         W",
    "            WWWWW              WWWW",
    "WW                       WWW      W",
    "W         WW      WWWWWWWWW     WWW",
    "WW                     WWW        W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
]
 